In [3]:
import numpy as np
from scipy.stats import rv_discrete
from matplotlib import pyplot as plt
import cvxpy as cp
import pickle
# import gurobipy

In [4]:
def gen_long_weights(N_grid):
    Weights = np.zeros(shape=(N_grid,N_grid))
    X = np.arange(0.5,N_grid,1)
    Y = np.arange(0.5,N_grid,1)
    cell_locs = []
    for i in range(N_grid):
        for j in range(N_grid):
            cell_locs.append([X[i],Y[j]])
    N_cells = N_grid*N_grid
    Weights = np.zeros(shape=(N_cells,N_cells))

    for i in range(N_cells):
        for j in range(N_cells):
            xpoints = [ cell_locs[i][0] + 0.5, cell_locs[i][0] - 0.5, cell_locs[j][0] + 0.5,  cell_locs[j][0] - 0.5 ]
            ypoints = [ cell_locs[i][1] + 0.5, cell_locs[i][1] - 0.5, cell_locs[j][1] + 0.5,  cell_locs[j][1] - 0.5 ]
            Weights[i,j] = np.sqrt((max(xpoints) - min(ypoints))**2 
                                   + (max(ypoints) - min(ypoints))**2)
            
    print("Spatial: longest",Weights)

In [5]:
gen_long_weights(2)

Spatial: longest [[1.41421356 2.23606798 2.23606798 2.82842712]
 [2.23606798 1.         2.82842712 1.41421356]
 [2.23606798 2.82842712 2.23606798 2.82842712]
 [2.82842712 1.41421356 2.82842712 1.41421356]]


In [10]:
N_grid = 2
Weights = np.zeros(shape=(N_grid,N_grid))
X = np.arange(0.5,N_grid,1)
Y = np.arange(0.5,N_grid,1)
cell_locs = []
for i in range(N_grid):
    for j in range(N_grid):
        cell_locs.append([X[i],Y[j]])
N_cells = N_grid*N_grid
Weights = np.zeros(shape=(N_cells,N_cells))

for i in range(N_cells):
    for j in range(N_cells):
        xpoints = [ cell_locs[i][0] + 0.5, cell_locs[i][0] - 0.5, cell_locs[j][0] + 0.5,  cell_locs[j][0] - 0.5 ]
        ypoints = [ cell_locs[i][1] + 0.5, cell_locs[i][1] - 0.5, cell_locs[j][1] + 0.5,  cell_locs[j][1] - 0.5 ]
        Weights[i,j] = np.sqrt((max(xpoints) - min(xpoints))**2 
                                + (max(ypoints) - min(ypoints))**2)
        
print("Spatial: longest",Weights)

Spatial: longest [[1.41421356 2.23606798 2.23606798 2.82842712]
 [2.23606798 1.41421356 2.82842712 2.23606798]
 [2.23606798 2.82842712 1.41421356 2.23606798]
 [2.82842712 2.23606798 2.23606798 1.41421356]]


In [9]:
cell_locs

[[0.5, 0.5], [0.5, 1.5], [1.5, 0.5], [1.5, 1.5]]

In [11]:
rand_weights = Weights
for i in range(N_grid):
    for j in range(N_grid):
        for k in range(N_grid):
            rand_weights[i,j] = min(rand_weights[i,j],rand_weights[i,k] + rand_weights[k,j] )

In [12]:
rand_weights == Weights

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])